In [2]:
import pandas as pd

In [16]:
df_1 = pd.read_excel('./purple_lotus_import/Transactions Report_Q1_2020.xlsx')

In [7]:
df_2 = pd.read_excel('./purple_lotus_import/Transactions Report_Q1_2021.xlsx')

In [8]:
df_3 = pd.read_excel('./purple_lotus_import/Transactions Report_Q2_2020.xlsx')

In [9]:
df_4 = pd.read_excel('./purple_lotus_import/Transactions Report_Q2_2021.xlsx')

In [10]:
df_5 = pd.read_excel('./purple_lotus_import/Transactions Report_Q3_2020.xlsx')

In [11]:
df_6 = pd.read_excel('./purple_lotus_import/Transactions Report_Q3_2021.xlsx')

In [12]:
df_7 = pd.read_excel('./purple_lotus_import/Transactions Report_Q4_2020.xlsx')

In [41]:
df_all = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7], axis=0, ignore_index=True)

In [25]:
df_all.to_csv('./purple_lotus_import/df_all.csv')

In [49]:
df_all.head()

,Order Items Date Closed Date,Order Items Ticketid,Order Items Ticketlineid,Order Items Ticket Type,Order Items Product Type,Order Items Product Brand,Order Items Productname,Order Items Product ID,Order Items Priceunit,Order Items Total Discounts,Order Items Total Net Sales,Order Items Total Sales Tax,Order Items Total Excise Tax,Order Items Total Cbt Tax,Order Items Total Units Sold Net,Order Items Total Gross Receipts,Order Items Total Cost Without Excise,Order Items Total Gross Profit,year_month
0,2020-03-07,ebb676ce-de6c-48e9-af38-b3c04e058bd8,1efcde55-6eb0-4dc8-a6ec-1839d4148bde,POS,CARTRIDGE,O.PEN VAPE,LEMON CAKE (1G),0046fe3f-a404-4c6f-bd6e-df7e113f2aee,36.99,1.85,35.14,3.95,4.05,3.51,1.00,46.65,15.00,20.14,2020-03
1,2020-01-11,90328ee7-6f83-41e3-aba8-6c45f236da21,74bc15a2-17a3-4924-9c60-94f906f31054,POS,CARTRIDGE,O.PEN VAPE,LEMON CAKE (1G),0046fe3f-a404-4c6f-bd6e-df7e113f2aee,36.99,1.85,35.14,3.95,4.05,3.51,1.00,46.65,15.00,20.14,2020-01
2,2020-03-14,8f0a8055-16be-4e4e-9d2f-75ac3a5a6148,a5bd3d34-302c-4603-8b14-881444f88e6c,POS,CARTRIDGE,O.PEN VAPE,LEMON CAKE (1G),0046fe3f-a404-4c6f-bd6e-df7e113f2aee,36.99,1.85,35.14,3.95,4.05,3.51,1.00,46.65,15.00,20.14,2020-03
3,2020-02-14,300ef582-9ff7-4e43-bbeb-64b5d3717312,419f91fd-dbe2-4007-86da-79d0493a7826,POS,CARTRIDGE,O.PEN VAPE,LEMON CAKE (1G),0046fe3f-a404-4c6f-bd6e-df7e113f2aee,36.99,1.85,35.14,3.95,4.05,3.51,1.00,46.65,15.00,20.14,2020-02
4,2020-03-14,8599654f-fc9c-44ad-8e66-46f24381fcf2,bddaef9c-eb48-45d3-bd6b-39cb3dcb93e9,POS,CARTRIDGE,O.PEN VAPE,LEMON CAKE (1G),0046fe3f-a404-4c6f-bd6e-df7e113f2aee,36.99,1.85,35.14,3.95,4.05,3.51,1.00,46.65,15.00,20.14,2020-03

In [42]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356939 entries, 0 to 1356938
Data columns (total 18 columns):
 #   Column                                 Non-Null Count    Dtype
---  ------                                 --------------    -----
 0   Order Items Date Closed Date           1356939 non-null  datetime64[ns]
 1   Order Items Ticketid                   1356939 non-null  object
 2   Order Items Ticketlineid               1356939 non-null  object
 3   Order Items Ticket Type                1356939 non-null  object
 4   Order Items Product Type               1356939 non-null  object
 5   Order Items Product Brand              1355238 non-null  object
 6   Order Items Productname                1356939 non-null  object
 7   Order Items Product ID                 1356939 non-null  object
 8   Order Items Priceunit                  1356939 non-null  float64
 9   Order Items Total Discounts            1356939 non-null  float64
 10  Order Items Total Net Sales            1356939 non-null  float64
 11  Order Items Total Sales Tax            1356939 non-null  float64
 12  Order Items Total Excise Tax           1356939 non-null  float64
 13  Order Items Total Cbt Tax              1356939 non-null  float64
 14  Order Items Total Units Sold Net       1356939 non-null  float64
 15  Order Items Total Gross Receipts       1356939 non-null  float64
 16  Order Items Total Cost Without Excise  1356939 non-null  float64
 17  Order Items Total Gross Profit         1356939 non-null  float64
dtypes: datetime64[ns](1), float64(10), object(7)
memory usage: 186.3+ MB

In [43]:
df_all['year_month'] = df_all['Order Items Date Closed Date'].dt.strftime("%Y-%m")

In [44]:
pd.options.display.float_format = '{:,.2f}'.format

In [45]:
df_groupby = df_all.groupby('year_month').sum()

In [46]:
df_rev_summary = df_groupby[['Order Items Total Net Sales', 'Order Items Total Gross Receipts', 'Order Items Total Cost Without Excise', 'Order Items Total Gross Profit']]

In [47]:
df_rev_summary

,Order Items Total Net Sales,Order Items Total Gross Receipts,Order Items Total Cost Without Excise,Order Items Total Gross Profit
year_month,,,,
2020-01,"1,437,382.14","1,929,967.27","730,682.25","706,699.89"
2020-02,"1,367,757.87","1,840,947.13","673,139.77","694,618.10"
2020-03,"1,604,152.70","2,156,830.26","804,640.89","799,511.81"
2020-04,"1,822,516.94","2,445,128.25","883,392.97","939,123.97"
2020-05,"2,079,755.03","2,782,638.08","973,308.61","1,106,446.42"
2020-06,"2,057,833.26","2,748,567.60","937,748.74","1,120,084.53"
2020-07,"2,117,888.89","2,817,794.83","934,835.16","1,183,053.74"
2020-08,"2,021,803.17","2,698,018.65","943,579.43","1,078,223.74"
2020-09,"1,915,795.57","2,555,698.02","869,834.91","1,045,960.66"
2020-10,"1,819,348.49","2,430,945.52","815,418.95","1,003,929.54"
2020-11,"1,760,766.83","2,362,394.57","888,538.84","872,227.99"
2020-12,"1,975,977.17","2,666,388.76","1,061,635.31","914,341.86"
2021-01,"1,927,698.61","2,604,471.70","1,016,702.98","910,995.63"
2021-02,"1,714,966.31","2,302,596.17","831,589.85","883,376.46"
2021-03,"2,056,833.82","2,766,766.43","1,047,576.62","1,009,257.20"
2021-04,"2,040,785.19","2,740,558.80","1,035,349.48","1,005,435.71"
2021-05,"2,009,883.46","2,694,243.52","991,308.09","1,018,575.37"
2021-06,"1,966,529.39","2,640,483.00","1,055,970.97","910,558.41"
2021-07,"2,045,464.68","2,738,792.77","1,044,202.59","1,001,262.09"
2021-08,"1,963,857.70","2,635,230.60","984,991.55","978,866.15"
2021-09,"1,941,104.23","2,600,490.29","939,225.07","1,001,879.16"

In [48]:
df_rev_summary.to_csv('./purple_lotus_import/rev_summary.csv')